### PR TITLE
Customize prefix name with an argument

### PR DESCRIPTION
**Pull request by zmbacker**
If you want change the prefix name 'admin' to 'manager'

e. g. `bin/rails g admin:scaffold_controller Post title:string content:text published:boolean --prefix_name=manager`

### CODE REVIEW

**Comment by dhampik** [comment]
Thanks for pull request, I also had some thoughts about this feature. Will check everything this weekend probably, cause it'll take some time to check everything and release a new version of the gem. Appreciate your efforts!

**Comment by zmbacker** [comment]
ok.

**Comment by dhampik** [comment]
Just an update. Really sorry for delay. This is on my tasks list, but unfortunately I can't tell the exact date when I'll check and merge this.

**Comment by zmbacker** [comment]
I have use the feature for my projects to generate many scaffolds. and no problem with them. I suggest you can merge it. when someone found something wrong with the feature, they will tell us. then correct it. it's open source. Do you think so?

**Comment by dhampik** [comment]
Merged into develop, I'm about to release rails 4.1-compatible version with this feature.
@zmbacker Thanks for taking part!

**Pull request closed without merging**
