### PR TITLE
add bootstrap option for views

### PR DESCRIPTION
**Pull request by joshuapaling**
For now, I've added ERB views only - no HAML yet. Resolves feature reqeust https://github.com/dhampik/rails-admin-scaffold/issues/6

There's still probably some improvements to make - but should be easy fixes from here.

Here's some screenshots of the bootstrap views:

screen shot 2014-10-12 at 9 20 53 pm
screen shot 2014-10-12 at 9 20 43 pm
screen shot 2014-10-12 at 9 20 38 pm
screen shot 2014-10-12 at 9 20 29 pm
screen shot 2014-10-12 at 9 20 23 pm

### CODE REVIEW

**Comment by dhampik** [comment]
Thanks a lot for your efforts. Looks good. I'll check and merge this PR soon.

**Comment by joshuapaling** [comment]
@dhampik have you had a chance to take a look at this?

**Comment by dhampik** [comment]
Sorry for not responding for so long. I have some personal issues, so can't do it right now (didn't even have access to computer). Hopefully I'll manage to accept PR and release new version of gem in 2 weeks or so.
Probably, for now it's better to put the following line into Gemfile to use this feature (in case if anyone needs it):

```
gem 'rails-admin-scaffold', github: 'joshuapaling/rails-admin-scaffold'
```

**Comment by dhampik** [comment]
Thank you for your efforts, @joshuapaling  :+1: !
I also added haml support, fixed some issues with checkboxes styling and released v0.1.0 of a gem.

**Comment by joshuapaling** [comment]
Nice work, thanks!

**Pull request merged**
